name: 'actions-comment-pull-request'
description: 'GitHub action to comment pull request with customizable message'
inputs:
  message:
    description: 'message to add to the PR'
    required: true
    default: 'Test message'

runs:
  using: 'node12'
  main: 'index.js'
